version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 905418070365.dkr.ecr.us-east-1.amazonaws.com
      - curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
  && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
      - sed -i -e '/experimental/ s/^#//g' /etc/apt/sources.list.d/nvidia-container-toolkit.list
      - sudo apt-get update
      - sudo apt-get install -y nvidia-container-toolkit
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t dust3r-inference .
      - docker tag dust3r-inference:latest 905418070365.dkr.ecr.us-east-1.amazonaws.com/dust3r-inference:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 905418070365.dkr.ecr.us-east-1.amazonaws.com/dust3r-inference:latest
artifacts:
  files:
    - "**/*"
